defaults:
  - base

trainer:
  experiment_name: frozenlake-main

model_config:
  model_name: local_deployment # should be registered in model_info
  max_concurrency: 16

model_info:
  local_deployment:
    provider_name: fireworks
    # model_name: accounts/fireworks/models/qwen2p5-72b-instruct
    model_name: rlor_model
    generation_kwargs:
      temperature: 1
      max_tokens: 8192

es_manager:
  train:
    env_configs:
      tags: ["FrozenLake"]
  val:
    env_configs:
      tags: ["FrozenLake"]

output_dir: ??